# Generated by Django 3.0.8 on 2020-09-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0003_auto_20200914_1158'),
        ('eshop_products', '0002_auto_20200913_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categoris',
            field=models.ManyToManyField(blank=True, to='eshop_product_category.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
