# Generated by Django 3.1.1 on 2020-10-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0005_auto_20200916_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
