# Generated by Django 3.0.8 on 2020-09-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0002_auto_20200914_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
