# Generated by Django 3.0.8 on 2020-09-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0003_auto_20200914_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=120, verbose_name='عنوان در url'),
        ),
    ]
