# Generated by Django 3.0.8 on 2020-09-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
    ]
