# Generated by Django 3.1.1 on 2020-09-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس های کاربران'},
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='text',
            new_name='Text',
        ),
    ]
