# Generated by Django 3.1.1 on 2020-09-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_setting', '0002_sitesetting_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='copy_right',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='متن کپی رایت'),
        ),
    ]
