# Generated by Django 3.1.1 on 2020-09-21 13:17

from django.db import migrations, models
import eshop_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_setting', '0003_sitesetting_copy_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_setting.models.uplad_image_path, verbose_name='تصویر'),
        ),
    ]
