# Generated by Django 3.1.1 on 2020-09-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order',
            new_name='order',
        ),
    ]
